# Generated by Django 2.2.2 on 2019-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['produto', 'quantidade', 'tipo_movimentacao'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='tipoproduto',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Produto', 'verbose_name_plural': 'Tipos de Produtos'},
        ),
        migrations.AddField(
            model_name='estoque',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da Última Atualização'),
        ),
    ]
