# Generated by Django 2.2.2 on 2019-06-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0003_auto_20190619_1852'),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now=True, verbose_name='Data e Hora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimento.Cliente')),
            ],
            options={
                'ordering': ['-data_hora'],
                'unique_together': {('cliente', 'data_hora')},
            },
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(editable=False, verbose_name='Nº do Item')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('item_cancelado', models.BooleanField(default=False, verbose_name='Item cancelado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.Venda')),
            ],
            options={
                'ordering': ['-venda__id', 'numero_item'],
            },
        ),
    ]
