"""
Django settings for mini_curso_django project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'na-=a1w%y-&475(a&=yxdfhzp@@qa5k9k0k833fbngmp&26u_u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'atendimento', # Outra opção: 'atendimento.apps.AtendimentoConfig'
    'estoque',
    'venda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mini_curso_django.urls'

# https://docs.djangoproject.com/pt-br/2.2/topics/templates/#support-for-template-engines
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # DIRS indica uma lista de diretórios que será usada na busca por templates.
        #
        # APP_DIRS, se True, indica que deverá ocorrer uma busca por templates dentro de uma pasta chamada  "templates"
        # em cada aplicação.
        #
        # A busca por templates ocorre primeiro em DIRS e depois na pasta "templates" (caso APP_DIRS==True). No primeiro
        # diretório que a engine do banco encontrar o template, a busca é encerrada.
        # Ex: mini_curso_django/templates
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mini_curso_django.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# https://docs.djangoproject.com/pt-br/2.2/intro/tutorial02/#database-setup
# https://docs.djangoproject.com/pt-br/2.2/ref/databases/#third-party-notes
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'pt-BR'

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# Although not all choices may be available on all operating systems.
# In a Windows environment this must be set to your system time zone.
# TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_L10N = True



"""
Quando for preciso pegar a data e hora corrente, prefira usar (A) "from django.utils import timezone; timezone.now()";
do que (B) "import datetime; datetime.datetime.now()".

Observação: Caso o USE_TZ seja True, o Django sempre vai armazenar a data e hora no timezone UTC, não importando se o dado
foi setado usando a abordagem (A) ou (B). Obs: O Django, no caso da data setada usando a abordagem (B), ajusta a data
de forma a persistí-la usando o timezone UTC. Veja o exemplo abaixo e o warning exibido pelo Django.

>>> from django.utils import timezone; import datetime;timezone.now(); datetime.datetime.now();
datetime.datetime(2019, 7, 18, 0, 40, 1, 870797, tzinfo=<UTC>)
datetime.datetime(2019, 7, 17, 21, 40, 1, 870917)

>>> from atendimento.models import Cliente
>>> Cliente.objects.filter(id=1).update(data_hora_cadastro=datetime.datetime.now())
..lib/python3.7/site-packages/django/db/models/fields/__init__.py:1421:
RuntimeWarning: DateTimeField Cliente.data_hora_cadastro received a naive datetime (2019-07-17 21:41:00.786135)   <<< Data setada.
while time zone support is active. RuntimeWarning)
1

>>> Cliente.objects.filter(id=1)[0].data_hora_cadastro
datetime.datetime(2019, 7, 18, 0, 41, 0, 786135, tzinfo=<UTC>)   <<< Data ajustada pelo Django.
"""


"""
Abaixo temos o exemplo do uso das abordagens (A) e (B) com o USE_TZ True e False.
Obs: is_naive = não há informação da timezone / is_aware = há informação do timezone

USE_TZ = True
>>> from django.utils import timezone; data_a = timezone.now(); data_a; timezone.is_naive(data_a); timezone.is_aware(data_a);
datetime.datetime(2019, 7, 18, 1, 5, 50, 462566, tzinfo=<UTC>)
False
True
>>> import datetime; data_b = datetime.datetime.now(); data_b; timezone.is_naive(data_b); timezone.is_aware(data_b);
datetime.datetime(2019, 7, 17, 22, 5, 59, 144102)
True
False


USE_TZ = False
>>> from django.utils import timezone; data_a = timezone.now(); data_a; timezone.is_naive(data_a); timezone.is_aware(data_a);
datetime.datetime(2019, 7, 17, 22, 7, 31, 590461)
True
False
>>> import datetime; data_b = datetime.datetime.now(); data_b; timezone.is_naive(data_b); timezone.is_aware(data_b);
datetime.datetime(2019, 7, 17, 22, 7, 37, 729420)
True
False
>>> 
"""
# https://docs.djangoproject.com/pt-br/2.2/topics/i18n/timezones/
USE_TZ = False




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/pt-br/2.2/howto/static-files/
# https://docs.djangoproject.com/pt-br/2.2/ref/settings/#static-files
# https://docs.djangoproject.com/pt-br/2.2/ref/settings/#staticfiles-finders

# Por padrão, cada aplicação poderá contar com uma pasta chamada "static" para armazenar os seus arquivos estáticos.
# Ex: mini_curso_django/atendimento/static
# Além disso, caso seja necessário, como por exemplo nos casos em que há arquivos estáticos compartilhados entre as
# apps, é possível através da variável STATICFILES_DIRS definir outros diretórios aonde desses arquivos poderão ser
# armazenados.
STATICFILES_DIRS = [
    # Ex: mini_curso_django/static
    os.path.join(BASE_DIR, "static"),
]

STATIC_URL = '/static/'

# Para servir arquivos estáticos em produção, leia:
# https://docs.djangoproject.com/pt-br/2.2/howto/static-files/deployment/
# STATIC_ROOT = 'deploy/static/'