# Generated by Django 2.2.2 on 2020-06-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_auto_20190717_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
    ]
